<a href="https://colab.research.google.com/github/AllordKel/goit-algo-hw-04/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

In [32]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
c = np.random.randint(1, 11, size=(5, 5))
print(c)

[[ 3  5  7 10 10]
 [ 8  7  4  7  4]
 [ 4  1  4  4  9]
 [ 4  9  6  4  5]
 [10  6  6  5  1]]


In [35]:
d = np.random.random((4, 4))
print(d)

[[0.19261782 0.15799666 0.30854511 0.57943814]
 [0.68846898 0.66163332 0.843337   0.68328819]
 [0.17140907 0.32133259 0.60208709 0.41543907]
 [0.42559975 0.65937644 0.78585669 0.0394896 ]]


In [36]:
e1 = np.random.randint(1, 11, size=5)
e2 = np.random.randint(1, 11, size=5)
print(e1)
print(e2)
print(e1+e2)
print(e1-e2)
print(e1*e2)

[10 10 10 10 10]
[8 6 7 5 8]
[18 16 17 15 18]
[2 4 3 5 2]
[80 60 70 50 80]


In [37]:
f1 = np.random.randint(1, 11, size=7)
f2 = np.random.randint(1, 11, size=7)
print(f1)
print(f2)
print(np.dot(f1, f2))

[5 3 5 2 5 5 8]
[9 9 5 5 2 8 1]
165


In [38]:
g1 = np.random.randint(1, 11, size=(2, 2))
g2 = np.random.randint(1, 11, size=(2, 3))
print(g1)
print(g2)
print(np.dot(g1, g2))

[[5 9]
 [2 2]]
[[5 8 7]
 [1 6 3]]
[[34 94 62]
 [12 28 20]]


In [39]:
h = np.random.randint(1, 11, size=(3, 3))
h_inv = np.linalg.inv(h)
print(h)
print(h_inv)

[[4 9 5]
 [7 4 5]
 [7 6 5]]
[[-3.33333333e-01 -5.00000000e-01  8.33333333e-01]
 [-6.61409461e-17 -5.00000000e-01  5.00000000e-01]
 [ 4.66666667e-01  1.30000000e+00 -1.56666667e+00]]


In [40]:
i = np.random.random((4, 4))
i1 = i.T
print(i)
print(i1)

[[0.32107389 0.64000133 0.12089555 0.12432509]
 [0.10978889 0.12477364 0.5591602  0.46432499]
 [0.53608022 0.32920571 0.73382631 0.65697681]
 [0.45745503 0.58804714 0.15927156 0.67158494]]
[[0.32107389 0.10978889 0.53608022 0.45745503]
 [0.64000133 0.12477364 0.32920571 0.58804714]
 [0.12089555 0.5591602  0.73382631 0.15927156]
 [0.12432509 0.46432499 0.65697681 0.67158494]]


In [41]:
j1 = np.random.randint(1, 11, size=(3, 4))
j2 = np.random.randint(1, 11, size=4)
print(j1)
print(j2)
print(np.dot(j1, j2))

[[ 7  9 10 10]
 [ 4  3 10  7]
 [ 1  8  3  4]]
[7 7 7 4]
[222 147 100]


In [42]:
k1 = np.random.random((2, 3))
k2 = np.random.random(3)
print(k1)
print(k2)
print(np.dot(k1, k2))

[[0.2405533  0.57100856 0.70561249]
 [0.74733409 0.31918936 0.27832399]]
[0.91029205 0.43584986 0.94125435]
[1.13200858 1.08138459]


In [43]:
l1 = np.random.randint(1, 11, size=(2, 2))
l2 = np.random.randint(1, 11, size=(2, 2))
print(l1)
print(l2)
print(l1*l2)

[[ 6  7]
 [ 4 10]]
[[9 7]
 [4 5]]
[[54 49]
 [16 50]]


In [44]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
print(m1)
print(m2)
print(np.dot(m1, m2))

[[7 6]
 [7 8]]
[[3 8]
 [4 3]]
[[45 74]
 [53 80]]


In [45]:
n = np.random.randint(1, 101, size=(5, 5))
print(n)
print(n.sum())

[[73 88 94 88 51]
 [92  7 51 31 89]
 [99 82 76 21 76]
 [40 62 66 47 26]
 [44 67 92 38 80]]
1580


In [46]:
o1 = np.random.randint(1, 11, size=(4, 4))
o2 = np.random.randint(1, 11, size=(4, 4))
print(o1)
print(o2)
print(o1-o2)

[[ 1  2  3 10]
 [ 3  5 10  6]
 [10  8  8  8]
 [ 2  6  1  7]]
[[ 2  3  7  4]
 [ 5  6  7  6]
 [ 6  3  6  3]
 [ 2 10 10  1]]
[[-1 -1 -4  6]
 [-2 -1  3  0]
 [ 4  5  2  5]
 [ 0 -4 -9  6]]


In [47]:
p1 = np.random.random((3, 3))
p2 = p1.sum(axis=1).reshape(-1, 1)
print(p1)
print(p2)

[[0.56160651 0.07503727 0.11427174]
 [0.32586978 0.90354923 0.13385456]
 [0.48509712 0.66569559 0.38896089]]
[[0.75091551]
 [1.36327357]
 [1.5397536 ]]


In [48]:
q = np.random.randint(1, 11, size=(3, 4))
print(q)
print(q**2)

[[ 7  1  5  9]
 [ 8  9  4 10]
 [ 7  9  9  9]]
[[ 49   1  25  81]
 [ 64  81  16 100]
 [ 49  81  81  81]]


In [49]:
r = np.random.randint(1, 51, size=4)
print(r)
print(np.sqrt(r))

[ 5 48  5 22]
[2.23606798 6.92820323 2.23606798 4.69041576]
